version: '3.8'

services:
  database:
    build:
      context: ./db 
      dockerfile: Dockerfile 
    ports:
      - "5432:5432" 

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"